In [2]:
import pandas as pd

# 1. Load the data
# Use 'engine="pyarrow"' to ensure it uses the library we installed
df = pd.read_parquet('products.parquet', engine='pyarrow')

# 2. Basic Exploration
print(f"Dataset Shape: {df.shape}")
display(df.info())    # Shows column types and memory usage
display(df.head())    # Shows the first 5 rows in a clean table

Dataset Shape: (40341, 6)
<class 'pandas.DataFrame'>
RangeIndex: 40341 entries, 0 to 40340
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     40341 non-null  str
 1   title          40341 non-null  str
 2   brand          40341 non-null  str
 3   price          40341 non-null  str
 4   category_path  40341 non-null  object
 5   description    40341 non-null  object
dtypes: object(2), str(4)
memory usage: 7.4+ MB

None

,product_id,title,brand,price,category_path,description
0,B004E2Z88O,Motorola Droid X Essentials Combo Pack,Verizon,14.99,"[Electronics, Computers & Accessories, Compute...",[all Genuine High Quality Motorola Made Access...
1,B07BJ7ZZL7,"QGHXO Band for Garmin Vivofit 4, Soft Silicone...",QGHXO,14.89,"[Electronics, Wearable Technology, Arm & Wrist...","[Compatibility, Custom designed for your preci..."
2,B00R6R82HS,"Fishfinder, Depth Finder Poly Sun Cover for 3""...",Westlake Market,10.99,"[Electronics, Car & Vehicle Electronics, Marin...",[Affordable and convenient way to cover your s...
3,B07Y6K1PRB,Novelty Cute Cartoon USB 2.0 Flash Drive Data ...,Fire Stone,8.98,"[Electronics, Computers & Accessories, Data St...",[This is a special usb stick that make as a cu...
4,B07848ZT9T,ANNKE 4K 16CH Security DVR Recorder with Human...,ANNKE,909.99,"[Electronics, Security & Surveillance, Surveil...",[ANNKE 16 channel 4K DVR security camera syste...

In [3]:
df.head()

,product_id,title,brand,price,category_path,description
0,B004E2Z88O,Motorola Droid X Essentials Combo Pack,Verizon,14.99,"[Electronics, Computers & Accessories, Compute...",[all Genuine High Quality Motorola Made Access...
1,B07BJ7ZZL7,"QGHXO Band for Garmin Vivofit 4, Soft Silicone...",QGHXO,14.89,"[Electronics, Wearable Technology, Arm & Wrist...","[Compatibility, Custom designed for your preci..."
2,B00R6R82HS,"Fishfinder, Depth Finder Poly Sun Cover for 3""...",Westlake Market,10.99,"[Electronics, Car & Vehicle Electronics, Marin...",[Affordable and convenient way to cover your s...
3,B07Y6K1PRB,Novelty Cute Cartoon USB 2.0 Flash Drive Data ...,Fire Stone,8.98,"[Electronics, Computers & Accessories, Data St...",[This is a special usb stick that make as a cu...
4,B07848ZT9T,ANNKE 4K 16CH Security DVR Recorder with Human...,ANNKE,909.99,"[Electronics, Security & Surveillance, Surveil...",[ANNKE 16 channel 4K DVR security camera syste...